### ISSUE TITLE
Does importing a custom actually schema work?

### ISSUE THREAD

**Issue by skybert** [GluuFederation/docker-openldap#3]
https://github.com/GluuFederation/docker-openldap/blob/04feb4d396ee77370f106f98a666a8ef71bb6844/scripts/ldap_initializer.py#L234

An extension to the LDAP schema is AFAIK normally a `.schema` file. A schema file is not the same as an LDIF file. `slapadd` will not add a schema file, only an `.ldif` (the name itself doesn't matter, but the format does).  From what I can read, `ldap_initializer.py` makes this call with the schema files in the tarball (if they're named .ldif`, that is):
```
root@a8341e984f1f:~# /opt/symas/bin/slapadd \
  -b \
  o=gluu  \
  -f /opt/symas/etc/openldap/slapd.conf  \
  -l  /tmp/s.schema
5ae09443 str2entry: entry -1 has no dn
slapadd: could not parse entry (line=1)
_#################### 100.00% eta   none elapsed            none fast!
Closing DB...
```
The method is called:
```python
import_custom_schema():
```
But it works off `ldif` files which are extracted from a tarball identified by a URL variable called:
```
GLUU_CUSTOM_SCHEMA_URL=myhost/my.schema.tar.gz
```

To me, this sounds like a few things are missing:
- the function should look for `.schema` files
- it should include these in the `ldap.conf` file
- it should then convert the `ldap.conf` to `ldif` and import the relevant portions regarding the schema changes.

Am I missing something here? :smiley:

**Comment by iromli** [comment]
Hi @skybert thanks for testing this functionality.

Indeed, the `slapadd` call inside `import_custom_schema` function doesn't work as expected.
I have tried modifying the function into:

```
slaptest_cmd = "/opt/symas/bin/slaptest"
slapaddt_cmd = "/opt/symas/bin/slapadd"
config = "/opt/symas/etc/openldap/slapd.conf"
config_dir = "/opt/symas/etc/openldap/slapd.d"

runcmd([slaptest_cmd, '-f', config, "-F", config_dir, "-u"])    
runcmd([slapadd_cmd, '-b', 'cn=schema,cn=config', '-f', config, '-l', file_path, "-F", config_dir])
```

but the entry is not show up in `ldapsearch` call, even when the actual file is exist under `/opt/symas/etc/openldap/slapd.d/cn\=config/cn\=schema` directory. I tried restarted the container to see the effect, but it still the same. I still investigate why the changes aren't reflected in `ldapsearch`

There's an alternative to use `ldapadd` instead of `slapadd`. By using `ldapadd`, the changes are reflected immediately. But there's a drawback using this executable. `ldapadd` requires the LDAP server to be online, hence I was thinking about deferring the call after the main entrypoint is running.

Any feedback are welcome.

**Comment by iromli** [comment]
Starting from OpenLDAP 2.4+, the schema can be added using OLC, so using `.schema` is not needed anymore. Though I'm not sure it's worked as advertised.

> To me, this sounds like a few things are missing:
>
>    the function should look for .schema files
>    it should include these in the ldap.conf file
>    it should then convert the ldap.conf to ldif and import the relevant portions regarding the schema changes.

**Comment by iromli** [comment]
Custom schema loading is fixed at 6632b3b957a53a763b4233cbd790f896405430bb.
The corresponding `gluufederation/openldap:3.1.2_dev` has been updated.

**Comment by skybert** [comment]
> Custom schema loading is fixed at 6632b3b.

Thanks for your prompt reply and fix. Your change almost fixes this feature, but for one wee thing: You must call `download_custom_schema()` before `ldap_configurator.py` runs. Patch attached (` git am  --ignore-space-change --ignore-whitespace --keep-cr <file>`).

[0001-ldap_configurator.py-needs-download_custom_schema-no.patch.txt](https://github.com/GluuFederation/docker-openldap/files/1960212/0001-ldap_configurator.py-needs-download_custom_schema-no.patch.txt)

**Comment by iromli** [comment]
@skybert thanks for pointing it out.

`download_custom_schema` is deprecated (will be removed on 3.1.3 release). User can mount a volume to `/ldap/custom_schema` directly.

**Comment by skybert** [comment]
Mhmm, ok We'll have to rework the orchestration of our cluster, then.

**Comment by iromli** [comment]
We will keep this function in 3.1.2 tag.

**Comment by iromli** [comment]
@skybert would you like to submit your patch via GitHub PR?

**Comment by skybert** [comment]
@iromli, done: https://github.com/GluuFederation/docker-openldap/pull/4

**Comment by iromli** [comment]
PR has been merged. Closing this issue.
